### ISSUE TITLE
make mentions scrollable

### ISSUE THREAD

**Issue by kisram** [fun-with-editions/akademie-static#103]
for some people [e.g. here](https://fun-with-editions.github.io/akademie-static/hammer-purgstall-von-joseph.html) the list of mentions is very long, let's put them in a scrollable div

**Comment by csae8092** [comment]
We should remove them anyways completely as we did in staribacher

**Comment by kisram** [comment]
staribacher still has them though? are we talking about the same thing?

**Comment by kisram** [comment]
Ah it was removed in the modal, I was talking about the person detail page

**Comment by kisram** [comment]
I will open a different issue for the mentions in the pop-ups, this is done
