### ISSUE TITLE
use "de-micro-editor" for interactivly change font style and size

### ISSUE THREAD

**Issue by linxOD** [fun-with-editions/akademie-static#19]

**Comment by tklampfl** [comment]
The content files of the edition provide the possibility to change the font size and the font family.

**Comment by kisram** [comment]
For some reason I haven't figured out yet, the select for the font size is present in the html, but it's not displayed

**Comment by linxOD** [comment]
for documentation: de-micro-editor.css contains css to hide the 2nd liste element on smaller screens.

**Comment by kisram** [comment]
@linxOD it was actually not the .css file, but a style tag added by editions.xsl :
```
                <style>
                    .navBarNavDropdown ul li:nth-child(2) {
                        display: none !important;
                    }
                </style>
```
