### ISSUE TITLE
integrate gh pages deployment via artifact/action

### ISSUE THREAD

**Issue by linxOD** [fun-with-editions/akademie-static#4]

**Comment by linxOD** [comment]
there are two types of deployment for GH Pages:
* Via Branch
* Via Github Action Artifact

Here is an example of you to deploy via artifact:
https://github.com/wiener-diarium/curved-conjunction/blob/main/.github/workflows/build.yml#L83

Currently, the deployment is done via Branch.
Check the repository settings for GH Pages to learn more.

**Comment by kisram** [comment]
I tried but I went back to the working solution via Branch, because I couldn't figure out why the Artifact version wasn't working+ the example is using Cache and Astro

**Comment by linxOD** [comment]
@kisram 
The current workflow is fine too. But in case you are interessted deployment via Artifact would require uploading an artifact before with https://github.com/actions/upload-pages-artifact

**Comment by kisram** [comment]
@linxOD I did that, but I kept getting an error that the artifact couldn't be deployed
