### ISSUE TITLE
responsive design

### ISSUE THREAD

**Issue by cfhaak** [fun-with-editions/akademie-static#43]
- [x] hide the top page image on mobile phones etc.

## landing page
- [x] less padding on heading
- [x]  text with chrome dev tools only 50% of screen

## tabulator 

- [x] https://tabulator.info/docs/6.2/layout#responsive-collapse make the tabulator tables repsonsive 

## footer

- [x] either hide logos or place them it in container with related text, to prevent them from flexing to different lines

**Comment by kisram** [comment]
Maybe I changed something in the meantime, but I can't reproduce the issue with the text only taking up 50% of the screen
