### ISSUE TITLE
integrate tei pyutils to add TEI root node attributes

### ISSUE THREAD

**Issue by linxOD** [fun-with-editions/akademie-static#5]

**Comment by kisram** [comment]
@linxOD our xml files already seem to have those, should we include this step anyway? same goes for #6

**Comment by csae8092** [comment]
> @linxOD our xml files already seem to have those, should we include this step anyway? same goes for #6

yes, please run the commands to add IDs in root element, as well as the denormalizing script when building the application. By doing so we can be sure that our data is reliable even if there were some changes in the original data folder
